class Setting {
    constructor(){
    this.equipment=[
        {
            'name':'倉儲機器人',
            'init':{
                'x':-66,
                'y':6,
                'z':130
            },
            'axis':[
                {
                    'name':'關節1',
                    'instance':null,
                    'dir':'z',
                    'max':0,
                    'mix':-55.3
                },
                {
                    'name':'關節2',
                    'instance':null,
                    'dir':'y',
                    'max':17,
                    'mix':0
                },
                {
                    'name':'關節3',
                    'instance':null,
                    'dir':'x',
                    'max':5.5,
                    'mix':-6.5
                },
            ]
        },
        {
            'name':'送刀機器人',
            'init':{
                'x':60,
                'y':97.5,
                'z':-175
            },
            'axis':[
                {
                    'name':'關節1',
                    'instance':null,
                    'dir':'z',
                    'max':53,
                    'mix':0
                },
                {
                    'name':'關節2',
                    'instance':null,
                    'dir':'y',
                    'max':0,
                    'mix':-7
                }
            ]
        },
        {
            'name':'刀倉機器人',
            'init':{
                'x':59,
                'y':7.2,
                'z':-155
            },
            'axis':[
                {
                    'name':'關節1',
                    'instance':null,
                    'dir':'z',
                    'max':35.5,
                    'mix':0
                },
                {
                    'name':'關節2',
                    'instance':null,
                    'dir':'y',
                    'max':18,
                    'mix':2.3039369583129883
                }
            ]
        },

    ];

    this.equipment_CNC=[
        {
            'name':'CNC 01',

            'tip':[
                {
                    'name':'error',
                    'instance':null,
                },
                {
                    'name':'run',
                    'instance':null,
                },
                {
                    'name':'idle',
                    'instance':null,
                }
            ]
        },
        {
            'name':'CNC 02',

            'tip':[
                {
                    'name':'error',
                    'instance':null,
                },
                {
                    'name':'run',
                    'instance':null,
                },
                {
                    'name':'idle',
                    'instance':null,
                }
            ]
        }
    ];
    //wh刀把點
    this.point_wh_toolholder=[
                {
                    'name':'w1',
                    'pos':[]
                },
                {
                    'name':'w2',
                    'pos':[]
                },
                {
                    'name':'w3',
                    'pos':[]
                },
                {
                    'name':'w4',
                    'pos':[]
                },
                {
                    'name':'w5',
                    'pos':[]
                },
                {
                    'name':'w6',
                    'pos':[]
                },
                {
                    'name':'w7',
                    'pos':[]
                },
                {
                    'name':'w8',
                    'pos':[]
                },
                {
                    'name':'w9',
                    'pos':[]
                },
        ];
    //cnc刀把點
    this.point_cnc_toolholder=[
        {
            'name':'t1',
            'pos':[]
        },
        {
            'name':'t2',
            'pos':[]
        },
        ];
    //貨物的點
    this.point_project=[

        ];
    //貨物到CNC的點
    this.point_cnc_move=[

        ];
    //toolholder ori
    this.toolholder =null;
    this.project =null;

    this.toolholders ={
        'wh':[],
        'cnc':[]
    };
    this.projects =[];

    }
}

export default {Setting :new Setting()}
